### ISSUE TITLE
Encore des petits détails

### ISSUE THREAD

**Issue by aminebzg** [Josias1997/typing-speed-test#7]
- Diminuer la hauteur du bouton "retour au site"

- Ajouter de l'espace à gauche de l'input, il est trop collé à la bordure gauche

- La hauteur de l'input est plus haute que celle des boutons timer/recommencer, il faudrait qu'elle soit pareille

- Mettre une police un peu plus épaisse, la police globale est un peu fine

- Changer la couleur du footer, de même couleur que le header

- Lorsqu'on clique sur "recommencer" après avoir fait un test (et qu'il y a les résultats d'affichés), ça supprime les résultats, tu peux faire en sorte que le composant résultat reste ?

- Supprimer la table des derniers scores

**Comment by Josias1997** [comment]
D'accord. Mon mail c'est hktech201@gmail.com

**Comment by aminebzg** [comment]
C'est ok tu peux supprimer ! :-)

**Comment by dev-josias** [comment]
D'accord.

**Comment by aminebzg** [comment]
Finalement le composant "Résultat" tu peux l'enlever comme avant
